[feat]: add small "copied" popup feature after clicking on "copy CID…
buidltools/dscan pull request #18
Opened 2022-03-11 17:53 UTC by atifcppprogrammer

The following is a preview of how the requisite tool tip appears, when the extension is used via the Chrome web browser.
<div align="center">
  <img src="https://user-images.githubusercontent.com/54069350/157922699-ce5d7b6a-ca15-4949-9be1-cf7de6073c28.png">
</div>

2022-03-13 13:58 UTC, AkhileshThite commented
@atifcppprogrammer few changes.

2022-03-13 14:03 UTC, atifcppprogrammer commented
> @atifcppprogrammer few changes.

@AkhileshThite, what changes are required ?

2022-03-13 14:13 UTC, AkhileshThite commented
> > @atifcppprogrammer few changes.
> 
> @AkhileshThite, what changes are required ?

Mentioned👆, please read the review.

2022-03-13 14:23 UTC, atifcppprogrammer commented
Hmmm @AkhileshThite, I dont see any comments there :disappointed:

2022-03-13 14:36 UTC, AkhileshThite commented
> Hmmm @AkhileshThite, I dont see any comments there 😞

![Screenshot 2022-03-13 at 8 06 15 PM](https://user-images.githubusercontent.com/68826419/158064600-50826083-1460-45ec-bc6f-1260cd09357a.png)

2022-03-13 14:37 UTC, AkhileshThite requested changes

2022-03-13 14:37 UTC, akhileshthite commented on src/css/popup.css
> +  border-radius: 0.2rem;
Increase border radius for more curve.

2022-03-13 14:37 UTC, akhileshthite commented on src/css/popup.css
> +  font-size: 1rem;
Must match the font style with current theme.

2022-03-13 14:37 UTC, akhileshthite commented on src/css/popup.css
> +  width: 80px;
Reduce the width a bit.

2022-03-13 14:37 UTC, akhileshthite commented on src/css/popup.css
> +  border: 0.2rem solid #cccdcd;
Try black, it should look professional.
You can choose the better one.

2022-03-13 14:38 UTC, atifcppprogrammer commented
> > Hmmm @AkhileshThite, I dont see any comments there disappointed
> 
> ![Screenshot 2022-03-13 at 8 06 15 PM](https://user-images.githubusercontent.com/68826419/158064600-50826083-1460-45ec-bc6f-1260cd09357a.png)

Thanks can see it now, not sure why it was not visible before.

2022-03-13 15:35 UTC, atifcppprogrammer commented
![Screenshot from 2022-03-13 20-34-27](https://user-images.githubusercontent.com/54069350/158067265-3f47af75-887f-4c8c-8ece-71b3d616cdac.png)
Hi @AkhileshThite, how about now ? the black border doesn't seem to work in my view

2022-03-13 15:47 UTC, atifcppprogrammer commented
Hi @AkhileshThite, how about now ? The black border doesn't quite work in my view, please let me know which of the following you prefer so i can push it, apart from the changes you requested above, i have only changed "Copied !" to "COPIED" to since all the other buttons are upper case as well
![Screenshot from 2022-03-13 20-40-26](https://user-images.githubusercontent.com/54069350/158067644-6e1d854c-c55d-40d3-9e89-d73e90ae1d92.png)
![Screenshot from 2022-03-13 20-44-47](https://user-images.githubusercontent.com/54069350/158067646-01e901b2-09ba-48fb-9e4e-6d3af2e598a9.png)

2022-03-13 16:07 UTC, AkhileshThite commented
> Hi @AkhileshThite, how about now ? The black border doesn't quite work in my view, please let me know which of the following you prefer so i can push it, apart from the changes you requested above, i have only changed "Copied !" to "COPIED" to since all the other buttons are upper case as well ![Screenshot from 2022-03-13 20-40-26](https://user-images.githubusercontent.com/54069350/158067644-6e1d854c-c55d-40d3-9e89-d73e90ae1d92.png) ![Screenshot from 2022-03-13 20-44-47](https://user-images.githubusercontent.com/54069350/158067646-01e901b2-09ba-48fb-9e4e-6d3af2e598a9.png)

Go with the first grey one 👍

2022-03-13 16:19 UTC, atifcppprogrammer commented
@AkhileshThite all set for review.

2022-03-13 17:02 UTC, atifcppprogrammer commented
Hi @AkhileshThite made a few minor changes in addition to the changes requested, change the letter spacing for the tool tip to match that of the buttons "FILE" and "FOLDER"

2022-03-14 06:15 UTC, AkhileshThite commented
> Hi @AkhileshThite made a few minor changes in addition to the changes requested, change the letter spacing for the tool tip to match that of the buttons "FILE" and "FOLDER"

Sure, I'll test and merge in few days.

2022-03-15 11:53 UTC, AkhileshThite approved these changes

2022-03-15 11:53 UTC, merged

2022-03-15 12:33 UTC, AkhileshThite commented
@atifcppprogrammer
Good work! 
All the updates are live with v2.1 release: https://chrome.google.com/webstore/detail/dscan-decentralized-qr-co/idpfgkgogjjgklefnkjdpghkifbjenap